<Project>
	<PropertyGroup>
	  <NoWarn>$(NoWarn);NU1507</NoWarn>
	</PropertyGroup>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <!-- If one didn't specify the package version, treat it as errors instead of warnings -->
  <PropertyGroup>
    <WarningsAsErrors>$(WarningsAsErrors);NU1008;NU1605</WarningsAsErrors>
  </PropertyGroup>
  <!-- Let projetcs can be compiled in .NET Framework (older version) when not installed -->
  <ItemGroup>
    <GlobalPackageVersion Include="NETStandard.Library" Version="2.0.3" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"/>
  </ItemGroup>
  <ItemGroup>
    <!-- This applies to ALL projects in the repository automatically -->
    <GlobalPackageVersion Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
  </ItemGroup>
  <!-- When uses `.NET Test Framework`, `Microsoft.NET.Test.Sdk` is used, but for older framework, uses the older version of `Microsoft.NET.Test.Sdk`  -->
  <!--
  <ItemGroup Condition="'$(IsLegacyFramework)' != 'true' And '$(TargetFramework)' != 'net452' And '$(TargetFramework)' != 'net472' And '$(TargetFramework)' != 'netstandard2.0'">
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsLegacyFramework)' == 'true' Or '$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net452' Or '$(TargetFramework)' == 'net472' Or '$(TargetFramework)' == 'netstandard2.0'">
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>
  -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>
  <!-- Use .ASP .NET Core Framework -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.App.Ref" Version="10.0.5" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.TeamFoundationServer.ExtendedClient" Version="20.256.2" />
  </ItemGroup>
  <!-- Mock File System -->
  <ItemGroup Condition="'$(IsLegacyFramework)' != 'true' And '$(TargetFramework)' != 'net452' And '$(TargetFramework)' != 'net472' And '$(TargetFramework)' != 'netstandard2.0'">
    <!-- abstraction of File system -->
    <PackageVersion Include="System.IO.Abstractions" Version="22.1.1" />
    <!-- Mock File System -->
    <PackageVersion Include="System.IO.Abstractions.TestingHelpers" Version="22.1.1" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsLegacyFramework)' == 'true' Or '$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net452' Or '$(TargetFramework)' == 'net472' Or '$(TargetFramework)' == 'netstandard2.0'">    <!-- abstraction of File system -->
    <PackageVersion Include="System.IO.Abstractions" Version="19.2.87" />
    <!-- Mock File System -->
    <PackageVersion Include="System.IO.Abstractions.TestingHelpers" Version="19.2.87" />
  </ItemGroup>
  <!-- abstraction of System Process -->
  <ItemGroup>
    <PackageVersion Include="System.Diagnostics.Abstractions" Version="1.0.9" />
  </ItemGroup>
  <!-- abstraction of System Process (used by older test framework such as `xUnit2`) -->
  <ItemGroup>
    <PackageVersion Include="Testably.Abstractions.FileSystem.Interface" Version="10.2.0" />
  </ItemGroup>
  <!-- Official utility packages of command line -->
  <ItemGroup>
    <PackageVersion Include="System.CommandLine" Version="2.0.5" />
  </ItemGroup>
  <!-- .NET SDK used by test framework -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>
  <!-- `MSBuild`, simulating `MSBuild` behaviour -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Build" Version="18.4.0" />
  </ItemGroup>
  <!-- Locator of `MSBuild` -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Build.Locator" Version="1.11.2" />
  </ItemGroup>
  <!-- Official utility packages about accessing version of NuGet package or .NET framework -->
  <ItemGroup>
    <!-- accessing version of  NuGet package -->
    <PackageVersion Include="NuGet.Protocol" Version="7.3.1" />
    <!-- accessing version of  .NET framework -->
    <PackageVersion Include="NuGet.Frameworks" Version="7.3.1" />
  </ItemGroup>
  <!-- Use traditional mode `VSTest` -->
  <!-- `NUnit` as Test Framework -->
  <ItemGroup>
    <PackageVersion Include="NUnit" Version="4.3.2" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.7.0" />
  </ItemGroup>
  <!-- `xUnit.v3` as Test Framework -->
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />
    <PackageVersion Include="xunit.v3.extensibility.core" Version="3.2.2" />
  </ItemGroup>
  <!-- package that checks the class or property contains specific words, it uses `xUnit.v2` as Test Framework -->
  <ItemGroup>
    <PackageVersion Include="TngTech.ArchUnitNET.xUnit" Version="0.13.3" />
  </ItemGroup>
  <!-- `xUnit.v2` as Test Framework -->
  <ItemGroup>
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
  <!-- Use modern mode `MTP` -->
  <!-- use `MSTest` as Test Framework -->
  <ItemGroup>
    <PackageVersion Include="MSTest.TestAdapter" Version="3.2.2" />
    <PackageVersion Include="MSTest.TestFramework" Version="3.2.2" />
    <PackageVersion Include="Microsoft.Testing.Extensions.VSTestBridge" Version="2.1.0" />
  </ItemGroup>
  <!-- use `NUnit` using `MTP` as Test Framework -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.TestPlatform" Version="18.4.0" />
    <PackageVersion Include="Microsoft.Testing.Platform.MSBuild" Version="2.2.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Testing.Platform" Version="2.2.1" />
  </ItemGroup>
  <!-- packages that makes the assertions be more fluent -->
  <ItemGroup Condition="'$(IsLegacyFramework)' != 'true' And '$(TargetFramework)' != 'net452' And '$(TargetFramework)' != 'net472' And '$(TargetFramework)' != 'netstandard2.0'">
    <PackageVersion Include="FluentAssertions" Version="8.9.0" />
    <PackageVersion Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsLegacyFramework)' == 'true' Or '$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net452' Or '$(TargetFramework)' == 'net472' Or '$(TargetFramework)' == 'netstandard2.0'">
    <PackageVersion Include="FluentAssertions" Version="5.10.3" />
    <PackageVersion Include="FluentValidation" Version="8.6.3" />
  </ItemGroup>
  <!-- packages that mock the interface and virtual class -->
  <ItemGroup>
    <PackageVersion Include="Moq" Version="4.20.72" />
  </ItemGroup>
  <!-- packages that checks the AST of class (including, check a class contains property named `property1`) -->
  <ItemGroup>
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
  </ItemGroup>
  <!-- Rolsyn -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.3.0" />
  </ItemGroup>
  <!-- Rolsyn used for tests -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing" Version="1.1.3" />
  </ItemGroup>
  <!-- Roslynator -->
  <ItemGroup>
    <PackageVersion Include="Roslynator.Analyzers" Version="4.15.0"/>
  </ItemGroup>
  <!-- SonarAnalyzer -->
  <ItemGroup>
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.25.0.139117" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.7" />
    <PackageVersion Include="System.ClientModel" Version="1.10.0" />
    <PackageVersion Include="System.Memory.Data" Version="10.0.3" />
  </ItemGroup>
   <!-- logger `ILogger` -->
  <Choose>
    <When Condition="'$(IsAtLeast8)' == 'true'">
      <ItemGroup>
        <PackageVersion Include="Microsoft.Extensions.Logging" Version="[11.0.0-preview.2.26159.112]" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="[11.0.0-preview.2.26159.112]" />
        <PackageVersion Include="Microsoft.Extensions.Options" Version="[11.0.0-preview.2.26159.112]" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="[11.0.0-preview.2.26159.112]" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="[11.0.0-preview.2.26159.112]" />
        <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="[11.0.0-preview.2.26159.112]" />
        <PackageVersion Include="Microsoft.Extensions.Primitives" Version="[11.0.0-preview.2.26159.112]" />
        <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
        <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />
      </ItemGroup>
    </When>
    <When Condition="'$(IsAtLeast6)' == 'true' And '$(IsAtLeast8)' != 'true' ">
      <ItemGroup>
          <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.Primitives" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
      <!-- NOT specify version of `Microsoft.Extensions.Logging` and its related packages as it is NOT supported -->
          <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.Primitives" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
          <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />
        </ItemGroup>
    </Otherwise>
  </Choose>
   <!-- Azure -->
  <ItemGroup>
    <PackageVersion Include="Azure.ResourceManager" Version="1.14.0" />
    <PackageVersion Include="Azure.Identity" Version="1.18.0" />
    <PackageVersion Include="Azure.Core" Version="1.51.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" Version="8.5.0" />
  </ItemGroup>
  <!--  -->
  <ItemGroup>
    <PackageVersion Include="System.Management" Version="10.0.2" />
  </ItemGroup>
  <!-- Registry key on Windows OS -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Win32.Registry" Version="5.0.0" />
  </ItemGroup>
  <!-- ACL on Windows OS -->
  <ItemGroup>
    <PackageVersion Include="System.Security.AccessControl" Version="6.0.1" />
  </ItemGroup>
  <!-- lock -->
  <ItemGroup>
    <PackageVersion Include="AsyncKeyedLock" Version="8.0.2" />
  </ItemGroup>
  <!-- EF Core -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="StackExchange.Redis" Version="2.11.0" />
  </ItemGroup>
  <!-- `Serilog` -->
  <ItemGroup>
    <PackageVersion Include="Serilog" Version="4.3.1" />
    <PackageVersion Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageVersion Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageVersion Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageVersion Include="Serilog.Enrichers.Demystifier" Version="1.0.3" />
    <PackageVersion Include="Serilog.Expressions" Version="5.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="10.0.0" />
  </ItemGroup>
  <!-- `Nuke` -->
  <ItemGroup>
    <PackageVersion Include="Nuke.Common" Version="10.1.0" />
  </ItemGroup>
  <!-- `PostSharp` -->
  <ItemGroup>
    <PackageVersion Include="PostSharp" Version="2026.0.6" />
    <PackageVersion Include="PostSharp.Patterns.Diagnostics" Version="2026.0.6" />
  </ItemGroup>
  <!-- `Appium.WebDriver` -->
  <ItemGroup>
    <PackageVersion Include="Appium.WebDriver" Version="8.1.0" />
    <PackageVersion Include="Selenium.WebDriver" Version="4.36.0" />
  </ItemGroup>
  <!-- `Polly` -->
  <ItemGroup>
    <PackageVersion Include="Polly" Version="8.6.6" />
    <PackageVersion Include="Polly.Core" Version="8.6.6" />
    <PackageVersion Include="Polly.RateLimiting" Version="8.6.6" />
    <PackageVersion Include="Polly.Extensions" Version="8.6.6" />
  </ItemGroup>
  <!-- other packages -->
  <ItemGroup>
    <PackageVersion Include="MiniExcel" Version="2.0.0-preview.2" />
    <PackageVersion Include="QRCoder" Version="1.7.0" />
    <PackageVersion Include="Otp.NET" Version="1.4.1" />
    <PackageVersion Include="Spectre.Console" Version="0.54.0" />
    <PackageVersion Include="MediatR" Version="14.0.0" />
  </ItemGroup>
  <!-- about command line (CLI)  -->
  <ItemGroup>
    <PackageVersion Include="CliWrap" Version="3.10.1" />
  </ItemGroup>
   <!-- about encoding -->
  <ItemGroup>
    <PackageVersion Include="System.Text.Encoding.CodePages" Version="10.0.7" />
  </ItemGroup>
  <!-- about sanitization -->
  <ItemGroup>
    <PackageVersion Include="System.Text.Encodings.Web" Version="10.0.7" />
  </ItemGroup>
  <!-- about file system globbing -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.7" />
  </ItemGroup>
  <!-- F# compiler and F# core library -->
  <ItemGroup>
    <PackageVersion Include="FSharp.Compiler.Service" Version="43.12.203" />
    <PackageVersion Include="FSharp.Core" Version="10.1.203" />
  </ItemGroup>
  <!-- My developed NuGet packages -->
  <ItemGroup>
    <PackageVersion Include="AiUtility.AiBaseUtilityServices" Version="[3.0.0-preview-1.0.0]" />
    <PackageVersion Include="AiUtility.ToolKits" Version="[3.0.0-preview-1.0.0]" />
    <PackageVersion Include="AiUtility.GeminiKits" Version="[3.0.0-preview-1.0.0]" />
    <PackageVersion Include="AiUtility.GeminiUtilityServices" Version="[3.0.0-preview-1.0.0]" />
  </ItemGroup>
  <!-- My developed NuGet packages -->
  <ItemGroup>
    <PackageVersion Include="EnumUtilityServices" Version="2.0.0" />
    <PackageVersion Include="CustomDataAnnotations" Version="2.4.0" />
    <PackageVersion Include="TypeConstants" Version="2.1.0" />
    <PackageVersion Include="MimeTypeConstants" Version="3.0.0" />
  </ItemGroup>
  <!-- My developed NuGet packages -->
  <ItemGroup>
    <PackageVersion Include="ExpressionTreeUtilityServices" Version="2.0.0" />
    <PackageVersion Include="ReflectionUtilityServices" Version="2.0.0" />
    <PackageVersion Include="LogNameUtilityFactories" Version="[2.0.0-preview-1.0.0]" />
    <PackageVersion Include="RegexUtilityServices" Version="2.0.0" />
    <PackageVersion Include="AssemblyUtilityServices" Version="[2.0.0-preview-1.0.0]" />
    <PackageVersion Include="ExceptionHandlingUtilityServices" Version="[3.0.0-preview-1.0.0]" />
    <PackageVersion Include="ExceptionFactories" Version="2.0.0" />
    <PackageVersion Include="ExceptionWrappers" Version="[3.0.0-preview-1.0.0]" />
    <PackageVersion Include="FileStreamUtilityServices" Version="2.1.0" />
    <PackageVersion Include="JsonUtilityServices" Version="2.0.0" />
    <PackageVersion Include="LoggerFactoryUtilityServices" Version="[5.0.0-preview-1.0.0]" />
    <PackageVersion Include="TaskUtilityServices" Version="2.0.0" />
    <PackageVersion Include="ThreadLevelLockingUtilityServices" Version="[2.0.0-preview-1.0.0]" />
    <PackageVersion Include="TypeUtilityServices" Version="2.0.0" />
    <PackageVersion Include="SerilogHelperServices" Version="2.0.0" />
    <PackageVersion Include="CoordinateUtilityServices" Version="2.0.0" />
    <PackageVersion Include="TransversalUtilityServices" Version="[2.0.0-preview-1.0.0]" />
    <PackageVersion Include="AzureUtilityServices" Version="[2.0.0-preview-1.0.0]" />
    <PackageVersion Include="ListItemUitilityServices" Version="2.0.0" />
    <PackageVersion Include="MathUtilityServices" Version="2.0.0" />
    <PackageVersion Include="StringUtilityServices" Version="2.0.0" />
    <PackageVersion Include="NetRuntimeUtilityServices" Version="[2.0.0-preview-1.0.0]" />
    <PackageVersion Include="ILoggerBuilderFactoryServices" Version="[2.0.0-preview-1.0.0]" />
    <PackageVersion Include="LoggingCodeTemplateGenerators" Version="2.0.0" />
    <PackageVersion Include="IOOperationUtilityServices" Version="[5.0.0-preview-1.0.0]" />
    <PackageVersion Include="EntriesAndTheirContentsServices" Version="[1.0.0-preview-1.0.0]" />
    <PackageVersion Include="SortingUtilityServices" Version="1.0.1" />
    <PackageVersion Include="CommonModels" Version="2.1.0" />
    <PackageVersion Include="ConsoleUtilityServices" Version="1.0.0" />
    <PackageVersion Include="FileCategorizationUtilityServices" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="CliUtilityServices" Version="[4.0.0-preview-1.0.0]" />
    <PackageVersion Include="EnvironmentUtilityServices" Version="3.0.0" />
    <PackageVersion Include="DriveInfoUtilityServices" Version="1.0.0-preview-1.0.0" />
    <PackageVersion Include="SymbolicLinkUtilityServices" Version="1.0.0-preview-1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="ProjectsVersionUtilityServices" Version="1.0.0" />
    <PackageVersion Include="SolutionUtilityServices" Version="[5.0.0-preview-1.0.0]" />
    <PackageVersion Include="PaketUtilityServices" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="ProgrammingLanguageUtilityServices" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="ScriptDiscoveryUtilityServices" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="SharedUtilityServices" Version="1.0.0" />
  </ItemGroup>
</Project>